N af toggle "dynaudnorm=peak=0.8:targetrms=-14dB"

Ctrl+UP cycle volume up
Ctrl+DOWN cycle volume down
# g-m --> Shows menu selection
n script-binding select/select-playlist
#/ script-binding commands/open
#
