# Basic limiter:
#   — threshold = -9dB
#   — attack = 45s
#   — release = 100s
#   — cuts -1dB of output
#   — level is for the auto-normalizer, which is disabled
#af="alimiter=limit=-9dB:attack=45:release=100:level_out=-1dB:level=disabled"
# Dynamic normalization without compression
#   - maxgain = 6dB
af="dynaudnorm=peak=0.8:targetrms=-14dB"
gapless-audio=yes
volume=90
volume-max=150
ytdl-raw-options="sleep-requests=3"
ytdl-raw-options-add="sleep-interval=1"
ytdl-raw-options-add="max-sleep-interval=4"
ytdl-raw-options-add="js-runtimes=node"
ytdl-raw-options-add="format=bestaudio/best"

[vgm]
profile="big-cache,fixes"

# Necessary for loading correctly
# audio forwards and backwards
# (load on to RAM only 3 min of audio from current position)
[big-cache]
cache=yes
cache-secs=180
demuxer-max-bytes=800MiB

[fixes]
af-add="afade=type=in:st=0:d=0.50"
af-add="afade=type=out:st=0:d=0.50"
#af-add="adeclick=threshold=10:method=save"

[remove-silence]
af-add="silenceremove=stop_periods=-1:stop_duration=0.3:stop_threshold=-30dB"

