#!/bin/bash

shopt -s expand_aliases
cd ~/storage/downloads/ || exit 1
saveCursor='\e7'
resetCursor='\e8'
openAlternateBuffer='\e[?1049h'
closeAlternateBuffer='\e[?1049l'
goTo1Line='\e[H'
# shellcheck source=../.bash_aliases
source ~/.bash_aliases
listOfUrls=()
readParams=(
    "-p" "URL: " "-e" "-n" "28"
)
readOrTimeout() {
    read -r "${readParams[@]}" URL
    [[ $? == 142 ]] && {
        printf "\n\n"
        return 142
    }
    return 0
}
resetAll() {
    [[ -n $PROMPT_DIRTRIM ]] && {
        printf '%b' \
            "$closeAlternateBuffer" \
            "$resetCursor"
    }
    exit 130
}
trap resetAll SIGINT

[[ -n $PROMPT_DIRTRIM ]] && {
    printf '%b' \
        "$saveCursor" \
        "$openAlternateBuffer" \
        "$goTo1Line"
}
while readOrTimeout ;do
    [[ $URL =~ ^https://youtu.be ]] && {
        listOfUrls+=("$URL")
        [[ -z ${readParams[5]} ]] && readParams+=("-t" "1.5")
        continue
    }
    printf "\e[F\e[2K"
    [[ -z "$URL" ]] && break
done

{
    printf '%s\n' "#$EPOCHSECONDS" "yt-dlp ${listOfUrls[*]}"
} >> ~/.bash_history &
# -s → Disables any kind of echoing from stdin
yt-dlp "${listOfUrls[@]}"
printf "\n\x1b[33;1;4m%s\x1b[0m" 'Download finished'
termux-media-scan ~/storage/downloads/ &>/dev/null &
wait
read -rsn 1
[[ -n $PROMPT_DIRTRIM ]] && {
    printf '%b' \
        "$closeAlternateBuffer" \
        "$resetCursor"
} || true

